### ISSUE TITLE
Empty names and publication count on first result

### ISSUE THREAD

**Issue by ghost** [emeryberger/CSrankings#68] opened 2016-08-13 09:15 UTC
Hi,
when selecting "Computer architecture ASPLOS, ISCA, MICRO" and deselecting every other option, the EPFL entry is empty, but is still ranked first. It seems there is a display problem.

Screenshot illustrating the situation attached. Browser used: chromium or firefox, with a fresh profile

![2016-08-13-111328_1308x752_scrot](https://cloud.githubusercontent.com/assets/5124130/17642430/18620414-6147-11e6-957d-f7f691618c2b.png)

**Comment by dants** [comment] 2016-08-13 16:13
Technion has a similar problem to EPFL -- when clicking on its triangle, no faculty member are shown (regardless of topic selection)

**Comment by emeryberger** [comment] 2016-08-14 00:15
I have narrowed down the problem (single word institution names) though I haven't figured out the cause yet. As a workaround, I am expanding out names or adding country names.

**Comment by emeryberger** [comment] 2016-08-14 00:28
Fixed with 6b86213d5e625dfe3e263f5c4ed0b040b0a8771e.

**Closed as completed by emeryberger** 2016-08-14 00:28 UTC
