### ISSUE TITLE
Adjusted counts are misleading

### ISSUE THREAD

**Issue by andrewcmyers** [emeryberger/CSrankings#265] opened 2017-03-30 13:47 UTC
The goal of avoiding double-counting seems good, but the implementation doesn't seem to be right yet.

Let's suppose a paper is written entirely by Cornell authors, one of whom happens to be a faculty member. It seems that the weight of the paper is divided by the number of authors. That seems a bit bizarre. A school that, say, encourages undergraduates to get involved in research looks worse if they put those students on the papers as authors.

Why not instead divide by the number of authors who are listed authors in the database, i.e., CS faculty at some institution?

**Comment by emeryberger** [comment] 2017-03-30 15:07
This is covered by the FAQ. More (true) authors almost certainly means more papers (because of the use of the geometric mean, this is effectively normalized by area). Including undergrads is appropriate when they are true authors. Counting only authors in the database creates incentives like preferring industrial authors over those affiliated with universities, working with students instead of working with faculty, discouraging faculty from accepting CS positions and steering them into industry, etc. etc. I do not see this changing, so I am closing the issue.

How is authorship count adjusted?

A single faculty member gets 1/N credit for a paper, where N is the number of authors, regardless of their affiliation or status (faculty, student, or otherwise). The number never changes. A paper can count for at most 1.0, in the case that all authors are / end up becoming faculty in the database.

The key downside to counting papers without adjusting for authors is that it would make it trivial to inflate the effect of writing a single paper simply by adding authors. Splitting authorship credit means that authors will be incentivized to appropriately treat authorship credit with the seriousness it deserves.

**Comment by emeryberger** [comment] 2017-03-30 15:08
Also:

How about adjusting the count only by faculty in the database (or some other means)?

Here are some of the numerous downsides of only including authors present in the database:

Authorship counts would be difficult to calculate (manually).
Authorship counts would be dynamic (that is, they would change over time). When an author dies and is no longer in the database, everyone else would have to have their credit increased (talk about perverse incentives).
It would create a perverse incentive for senior faculty to have their junior collaborators not get tenure (since they would then likely leave the database).
It would favor collaboration with industry (not in the database) over collaboration with academics. Note that for very good reasons, companies do not generally provide public access to their employee directories.
It would create a disincentive for faculty to see their students get faculty appointments (since it would reduce credit).

**Closed as completed by emeryberger** 2017-03-30 15:07 UTC

**Comment by andrewcmyers** [comment] 2018-06-03 17:36
None of these issues or perverse incentives seem to me to be on the same order of magnitude as the existing perverse incentive that the current system creates to avoid involving students (especially undergraduates and junior PhD students) in research. There will be perverse incentives no matter what system is chosen, so the existence of perverse incentives can be used to justify any position you like. What is important is to evaluate the relative impact of the incentives that the system introduces.

**Comment by fycus-tree** [comment] 2018-06-03 18:38
@andrewcmyers Related, there's issue #562 which proposes maintaining multiple scoring methods, in a "choose your own adventure" way of stating that "what's best depends on what you value". A few of the proposals there would remove this author count normalization.

**Comment by emeryberger** [comment] 2018-06-03 20:26
For what it's worth, I dispute the notion that there is a disincentive to involve students in research here. First: the ACM (for example) has very clear rules about authorship. If the students are materially involved in the paper per ACM rules, then they *must* be listed; it's not your choice. If they are not, then you are not permitted by ACM rules to include them as authors. Second: if you want to publish papers, students will almost invariably be involved as major contributors; that is, as authors. If you want to publish more papers, you will need to involve more authors, and the most natural authors are your students. I did a regression on publications and authors and it turns out that there is an entirely clear linear relationship between number of papers published and number of authors.

**Comment by andrewcmyers** [comment] 2018-06-03 21:51
Almost everything you say is entirely compatible with there being a disincentive to involve students. Different students can contribute to different degrees. If their contribution is relatively small, as is often the case with undergraduates and junior graduate students, then they should still be listed as authors, as you point out, diluting the value of the paper.

I don't see why the correlation between the number of authors and the number of papers published is surprising or relevant here. The question is regarding the marginal impact of involving a given student in research. Unless they are able to contribute at the same level as the other authors, the optimal choice for csrankings glory is to not involve such students.

I would also suggest that this policy adds a systematic bias against more systems-oriented research areas that benefit strongly from the involvement of junior students who can help with implementation and evaluation.

**Comment by emeryberger** [comment] 2018-06-04 00:43
I think it's worth reading the current ACM guidelines. They rule out listing anyone as authors whose contribution is (as you suggest above) limited to implementation and/or evaluation.

-----
https://www.acm.org/publications/policies/authorship
-----

Anyone listed as Author on an ACM manuscript submission must meet all the following criteria:

* they have made substantial intellectual contributions to some components of the original work described in the manuscript; and
* they have participated in drafting and/or revision of the manuscript and
* they are aware the manuscript has been submitted for publication; and
* they agree to be held accountable for any issues relating to correctness or integrity of the work.
Other contributors may be acknowledged at the end of the paper, before the bibliography.

**Comment by andrewcmyers** [comment] 2018-06-04 02:10
I understand the ACM policies, but they are largely beside the point. I want to be able to offer undergraduates a carrot, authorship of a paper, to motivate them to help with research projects. Of course, I also get them involved in drafting or revising parts of the manuscript related to their work on the project, so they do meet the ACM criteria. But the current csrankings design disincentivizes this mode of involvement.

**Comment by emeryberger** [comment] 2018-06-07 16:16
If anyone has contributed at the level of being qualified as an author, then they are helping get the work done in the paper, and therefore helping get the paper out / out faster.

**Comment by andrewcmyers** [comment] 2018-06-07 16:26
You're not addressing the core issue of incentives. Of course, additional authors are helping get the paper out. The question now becomes: are they helping *enough* to justify the dilution of the paper's value as a whole? A faculty member optimizing for csrankings impact needs to think carefully about that question. Note that it is also not necessarily germane to argue from data about  how people have behaved before csrankings started torquing incentives.

**Comment by andrewcmyers** [comment] 2018-06-07 17:35
Let me try one more argument. I see a key goal of CSrankings as helping students decide which schools to join and which advisors to work with. The current system ranks advisors higher if they are careful to work with few, above-average students. That means the ranking can mislead students about where they are likely to find an advisor.

**Comment by dgruss** [comment] 2019-01-09 09:49
I always add undergraduate students on my papers when they contributed a small piece, significant enough to be co-author, often several of them. So for the 8 papers counted for me, I do get 1.4 after scaling although I've been leading author (doing most of the work) on all but one. This creates incentives to not add undergraduate students to papers.

**Comment by dgruss** [comment] 2019-01-09 09:51
I agree with @andrewcmyers that as is, this would mislead students. As I would rank much higher if I would just take the results from my undergraduate students and just acknowledge them in the paper, but don't offer them co-authorship.

**Comment by emeryberger** [comment] 2019-01-09 21:03
Co-authorship is not a gift to be offered. Either someone is an author or they are not. If they meet this threshold, you ethically have to include them.

http://www.acm.org/publications/policies/authorship

Anyone listed as Author on an ACM manuscript submission must meet all the following criteria:

* they have made substantial intellectual contributions to some components of the original work described in the manuscript; and
* they have participated in drafting and/or revision of the manuscript and
* they are aware the manuscript has been submitted for publication; and
* they agree to be held accountable for any issues relating to correctness or integrity of the work.
Other contributors may be acknowledged at the end of the paper, before the bibliography.

**Comment by dgruss** [comment] 2019-01-09 21:50
I do offer co-authorship, by inviting them to write something for the manuscript.
I do offer people from other universities co-authorship, by inviting them to write something for the manuscript.
Now, in future when a student did great in some project work and would like to co-author a paper on the same topic, instead of offering them to write something and by that co-author the paper, I will tell them: "No. Emery said universities where undergraduate students co-author papers shall be ranked lower. Surely you don't want your university to be ranked lower."
But thanks for the information.

**Comment by dgruss** [comment] 2019-01-09 22:02
Note that for undergraduate (and graduate) students, you often invest more time in letting them co-author than it would take to do the same work on your own.
But for the undergraduate (or graduate) student it's of immense value to get this experience to build up their career.
And then, undergraduate (or graduate) students tend to move somewhere else for their PhD. So you don't even benefit from it on the long run in many cases.
So you invest more time in total and the university is ranked lower, indicating that it is a worse place for students to get their research careers started.
If that's what is the goal then I have nothing to complain about.

**Comment by andrewcmyers** [comment] 2019-01-09 22:34
Emery, you've been concerned elsewhere about creating perverse incentives with your ranking system, and rightly so. But in this case you seem stoutly resistant to considering the incentives being created, even though I would consider them to be more significant than incentives you have worried about in other discussions.

Should I try to get undergraduates involved in research? Your ranking system says, "only if they contribute at least 1/N" where N is the number of authors. Few undergrads will meet this condition, even at an elite institution. The same argument even applies to junior graduate students.
