### ISSUE TITLE
More on incentives/by-area rankings/

### ISSUE THREAD

**Issue by eagichtein** [emeryberger/CSrankings#772] opened 2018-04-04 14:47 UTC
One more issue with current ranking scheme which I do not believe has been mentioned: the current ranking scheme discourages faculty from publishing in new areas, but rather to concentrate publishing in their 1 "home" area. 

For example, let's say I primarily publish in Web/IR, but have a paper with a student that fits better in a top NLP conference. Problem: if I publish this 1 paper in an NLP conference, it  drags *down* my institution's score in NLP area, since now the institution's NLP area includes a faculty with 0.5 normalized pub count in NLP, and the *institution* average for NLP goes down instead of up. Seems broken.

I don't have a proposed solution, but perhaps smarter people here will propose one.

**Comment by marcniethammer** [comment] 2018-04-04 15:31
Isn't the way the rankings are computed (I might be wrong) that the score is cumulative within the areas, but then gets aggregated across areas via a geometric mean? If this is the case, then it should not drag down the ranking in the NLP area in your example. Does it?

**Comment by fycus-tree** [comment] 2018-04-04 19:51
I agree with marcniethammer -- CSRankings doesn't currently do averages-per-area, it does totals-per-area. So this isn't an actual problem. The real problem (as I mentioned in #562) is that publishing in "rare" fields helps your score a lot more than publishing in "common" fields, because the final score is a geometric mean across all fields. NLP and Web/IR are kind of equal, but a Comp. Econ paper is worth far more than an AI or CV paper. (In fact, try disabling just the "Comp Econ" field on CSRankings, you'll see Berkeley and Stanford go from being tied to being almost 10% separated).

**Comment by marcniethammer** [comment] 2018-04-04 19:58
I guess this would suggest not doing the geometric mean, but computing everything cumulative. Doing this would have the added benefit that there would be no issue when adding smaller areas that may not have been that well established yet (as long as the conferences are high quality). Everything would then get counted equally (a paper is a paper regardless of area). And, of course, one could still have within-area rankings without any issue. Am I missing something?

**Comment by eagichtein** [comment] 2018-04-04 20:14
@fycus-tree and @marcniethammer : that makes alot more sense, i was confused by the reported scores that actually are not exactly the sum of adjusted counts but are off by 1.0 :-)

So - yes, agree on theory and withdraw concern. 
@emeryberger :  I think there is an off-by-one bug which does not affect the area rankings, but adds 1.0 to every institutions' area count (easiest to see for areas/universities with only 1 faculty member in that area). It may be a feature, not a bug -- but the values as shown currently are confusing.

As for overall rankings combining popular vs. unpopular areas -- IMO it would make sense to stay consistent, i.e., just do add area counts as @marcniethammer suggests.

**Comment by fycus-tree** [comment] 2018-04-04 21:38
@eagichtein It's not an off by one bug :) The issue is that the geometric mean is a product mean, so if a university has 0 publications in any area, it'd get a zero score overall. So adding a one makes the products work out smoothly (areas with no publications don't affect the product). 

The code is pretty readable. [Add up author adjusted counts per professor](https://github.com/emeryberger/CSrankings/blob/gh-pages/util/generate-all-pubs.py#L111) then [add up the authors at every university per area](https://github.com/emeryberger/CSrankings/blob/gh-pages/csrankings.js#L664) then take the [geometric mean over areas](https://github.com/emeryberger/CSrankings/blob/gh-pages/csrankings.js#L713)

The total counting (no normalization!) thing is in one of the proposed metrics #562 ([comment](https://github.com/emeryberger/CSrankings/issues/562#issuecomment-345479540)). I'd like to see it at least available as a selection. If I understand correctly, Emery's "goal" with the normalization is to account for the fact that some fields have more publications/bigger venues/etc. But the quality of the normalization depends on the quality of the categories and how they're weighted. I don't think it's clear to me that there's a "better" answer, but I think making both available is a good move.

**Comment by emeryberger** [comment] 2018-04-08 20:43
I am going to close this issue since I think it's been addressed by the comments (thanks @fycus-tree and @marcniethammer ).

**Closed as completed by emeryberger** 2018-04-08 20:43 UTC
